spring:
 application:
  name: "accounts"
 profiles:
  active: "qa"

build:
 version: 2.0
  
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/  
      
info:
  app:
    name: "accounts"
    description: "Zetta Bank Accounts Application"
    version: "1.0.0"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true
   
