server:
  port: 8071
spring:
  application:
    name: "configserver"
  profiles:
    active:
    - git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/zaiba-khan/git-repository.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true